# Generated by Django 5.2.13 on 2026-04-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.CharField(db_column='ContestID', max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('start_time', models.DateTimeField(db_column='StartTime')),
                ('end_time', models.DateTimeField(db_column='EndTime')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'Contests',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.CharField(db_column='ProblemID', max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('statement', models.TextField(db_column='Statement')),
                ('category', models.CharField(choices=[('Algebra', 'Algebra'), ('Calculus', 'Calculus'), ('Polynomials', 'Polynomials'), ('Other', 'Other')], db_column='Category', max_length=50)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Problems',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('password_hash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Participant', 'Participant')], db_column='Role', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('rubric_id', models.AutoField(db_column='RubricID', primary_key=True, serialize=False)),
                ('step_description', models.TextField(db_column='StepDescription')),
                ('max_points', models.PositiveIntegerField(db_column='MaxPoints')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
            ],
            options={
                'db_table': 'Rubrics',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(db_column='SubmissionID', primary_key=True, serialize=False)),
                ('answer_text', models.TextField(db_column='AnswerText')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='SubmittedAt')),
                ('score', models.IntegerField(blank=True, db_column='Score', default=0, null=True)),
                ('grading_status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded')], db_column='GradingStatus', default='Pending', max_length=20)),
                ('contest', models.ForeignKey(db_column='ContestID', on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'Submissions',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.PositiveIntegerField(db_column='PointValue')),
                ('contest', models.ForeignKey(db_column='ContestID', on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
            ],
            options={
                'db_table': 'ContestProblems',
                'unique_together': {('contest', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(db_column='TotalScore', default=0)),
                ('rank', models.IntegerField(db_column='Rank')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='LastUpdated')),
                ('contest', models.ForeignKey(db_column='ContestID', on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'Leaderboards',
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('registration_id', models.AutoField(db_column='RegistrationID', primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_column='RegisteredAt')),
                ('contest', models.ForeignKey(db_column='ContestID', on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'ContestRegistrations',
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
