# Generated by Django 6.0.4 on 2026-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='reference_solution',
            field=models.TextField(blank=True, db_column='ReferenceSolution', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, db_column='AIFeedback', null=True),
        ),
    ]
