# Generated by Django 6.0.4 on 2026-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rubric_reference_solution_submission_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='max_points',
            field=models.PositiveIntegerField(db_column='MaxPoints', default=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='reference_solution',
            field=models.TextField(blank=True, db_column='ReferenceSolution', null=True),
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
