# Generated by Django 5.2.13 on 2026-04-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='created_by',
        ),
    ]
