# Generated by Django 5.2.13 on 2026-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_problem_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='PasswordHash', max_length=128, null=True),
        ),
    ]
