# Generated by Django 5.2.13 on 2026-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contest_created_by_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='PasswordHash', max_length=128),
        ),
    ]
